"""知识库事实库（双语）。

每条事实都带有唯一锚点（anchor_zh / anchor_en）。锚点的作用是：
切分完成后，可以用锚点在 chunk 里反查，自动得到该事实对应的 gold chunk id，
从而在不需要人工标注的情况下生成 Context Precision 的 ground truth。

唯一性由 validate() 强制校验，避免出现"锚点命中多个 chunk"导致标注错误。
"""

from __future__ import annotations

from typing import Any

# 文档类型：handbook(员工手册) / compliance(合规指南) / tech_spec(技术规范) / architecture(架构文档)
FACTS: list[dict[str, Any]] = [
    # ---------------- 员工手册 ----------------
    {
        "key": "annual_leave_days",
        "doc_type": "handbook",
        "section_zh": "年假",
        "section_en": "Annual Leave",
        "zh": "员工入职满一年后，每个自然年度享有 15 个工作日带薪年假。年假申请需提前 3 个工作日提交至直属主管审批。",
        "en": "After completing one year of service, employees are entitled to 15 working days of paid annual leave per calendar year. Requests must be submitted to the direct manager 3 working days in advance.",
        "anchor_zh": "15 个工作日带薪年假",
        "anchor_en": "15 working days of paid annual leave",
        "q_zh": "员工每年有多少天年假？",
        "q_en": "How many days of annual leave are employees entitled to?",
        "a_zh": "入职满一年后每个自然年度 15 个工作日带薪年假，需提前 3 个工作日申请。",
        "a_en": "15 working days of paid annual leave per calendar year after one year of service, requested 3 working days in advance.",
    },
    {
        "key": "sick_leave_deadline",
        "doc_type": "handbook",
        "section_zh": "病假",
        "section_en": "Sick Leave",
        "zh": "员工请病假须在当日上午 09:30 前通过人事系统提交申请；连续病假超过 2 个工作日需提供二级以上医院证明。",
        "en": "Sick leave must be submitted through the HR system before 09:30 on the same day. Absences longer than 2 consecutive working days require a medical certificate from a tier-2 hospital or above.",
        "anchor_zh": "上午 09:30 前通过人事系统提交",
        "anchor_en": "before 09:30 on the same day",
        "q_zh": "请病假需要在什么时间之前提交？",
        "q_en": "By what time must sick leave be submitted?",
        "a_zh": "须在当日上午 09:30 前通过人事系统提交；连续超过 2 个工作日需提供医院证明。",
        "a_en": "Before 09:30 on the same day; absences over 2 consecutive working days need a medical certificate.",
    },
    {
        "key": "probation_period",
        "doc_type": "handbook",
        "section_zh": "试用期",
        "section_en": "Probation",
        "zh": "新员工试用期为 6 个月，试用期内每季度进行一次绩效回顾，试用期考核通过后方可转正。",
        "en": "The probation period for new employees is 6 months, with a performance review each quarter. Confirmation follows a successful probation assessment.",
        "anchor_zh": "试用期为 6 个月",
        "anchor_en": "probation period for new employees is 6 months",
        "q_zh": "新员工的试用期是多久？",
        "q_en": "How long is the probation period for new employees?",
        "a_zh": "试用期为 6 个月，每季度进行一次绩效回顾。",
        "a_en": "6 months, with a performance review each quarter.",
    },
    {
        "key": "travel_reimbursement_window",
        "doc_type": "handbook",
        "section_zh": "差旅报销",
        "section_en": "Travel Reimbursement",
        "zh": "差旅费用须在行程结束后 30 个自然日内提交报销单据，逾期未提交的需由部门负责人书面说明。",
        "en": "Travel expenses must be submitted within 30 calendar days after the trip ends. Late submissions require written justification from the department head.",
        "anchor_zh": "行程结束后 30 个自然日内提交报销",
        "anchor_en": "within 30 calendar days after the trip ends",
        "q_zh": "差旅报销需要在多久内提交？",
        "q_en": "What is the deadline for submitting travel expenses?",
        "a_zh": "行程结束后 30 个自然日内提交，逾期需部门负责人书面说明。",
        "a_en": "Within 30 calendar days after the trip ends; late submissions need written justification.",
    },
    {
        "key": "overtime_compensation",
        "doc_type": "handbook",
        "section_zh": "加班与调休",
        "section_en": "Overtime and Time Off in Lieu",
        "zh": "经审批的加班可折算为调休，调休有效期为 90 天，逾期自动作废且不予折现。",
        "en": "Approved overtime may be converted into time off in lieu, valid for 90 days. Unused balances expire and are not cashed out.",
        "anchor_zh": "调休有效期为 90 天",
        "anchor_en": "valid for 90 days",
        "q_zh": "加班折算的调休有效期是多久？",
        "q_en": "How long is overtime time-off-in-lieu valid?",
        "a_zh": "调休有效期为 90 天，逾期作废且不折现。",
        "a_en": "90 days; unused balances expire and are not cashed out.",
    },
    {
        "key": "remote_work_days",
        "doc_type": "handbook",
        "section_zh": "远程办公",
        "section_en": "Remote Work",
        "zh": "员工每周最多可申请 2 天远程办公，需提前一个工作日经直属主管审批，核心会议日不得远程。",
        "en": "Employees may request up to 2 remote working days per week, approved by the direct manager one working day in advance. Core meeting days are on-site.",
        "anchor_zh": "每周最多可申请 2 天远程办公",
        "anchor_en": "up to 2 remote working days per week",
        "q_zh": "每周可以远程办公几天？",
        "q_en": "How many remote working days are allowed per week?",
        "a_zh": "每周最多 2 天，需提前一个工作日审批，核心会议日不得远程。",
        "a_en": "Up to 2 days per week, approved one working day in advance; core meeting days are on-site.",
    },
    {
        "key": "resignation_notice",
        "doc_type": "handbook",
        "section_zh": "离职流程",
        "section_en": "Resignation",
        "zh": "员工主动离职须提前 30 天提交书面通知，并完成工作交接与资产归还后方可办理离职手续。",
        "en": "Employees resigning voluntarily must give 30 days written notice and complete handover and asset return before offboarding.",
        "anchor_zh": "提前 30 天提交书面通知",
        "anchor_en": "must give 30 days written notice",
        "q_zh": "离职需要提前多久通知公司？",
        "q_en": "How much notice is required for resignation?",
        "a_zh": "提前 30 天提交书面通知，并完成交接与资产归还。",
        "a_en": "30 days written notice, plus handover and asset return.",
    },
    {
        "key": "training_budget",
        "doc_type": "handbook",
        "section_zh": "培训预算",
        "section_en": "Training Budget",
        "zh": "每位员工每个自然年度享有 8000 元培训预算，可用于外部课程与认证考试，需事先经部门负责人审批。",
        "en": "Each employee has an annual training budget of CNY 8000 for external courses and certification exams, subject to prior approval by the department head.",
        "anchor_zh": "8000 元培训预算",
        "anchor_en": "annual training budget of CNY 8000",
        "q_zh": "员工的年度培训预算是多少？",
        "q_en": "What is the annual training budget per employee?",
        "a_zh": "每人每自然年度 8000 元，用于外部课程与认证考试，需事先审批。",
        "a_en": "CNY 8000 per employee per calendar year for external courses and certifications, subject to prior approval.",
    },
    # ---------------- 合规指南 ----------------
    {
        "key": "gift_value_limit",
        "doc_type": "compliance",
        "section_zh": "礼品与招待",
        "section_en": "Gifts and Hospitality",
        "zh": "员工不得收受或提供价值超过 200 元的礼品、餐饮或娱乐招待；超限礼品须登记并上交合规部门。",
        "en": "Employees must not accept or offer gifts, meals or entertainment worth more than CNY 200. Items above the limit must be registered and surrendered to Compliance.",
        "anchor_zh": "价值超过 200 元的礼品",
        "anchor_en": "worth more than CNY 200",
        "q_zh": "收受礼品的价值上限是多少？",
        "q_en": "What is the value limit for accepting gifts?",
        "a_zh": "不得超过 200 元，超限礼品须登记并上交合规部门。",
        "a_en": "CNY 200; items above the limit must be registered and surrendered to Compliance.",
    },
    {
        "key": "conflict_of_interest",
        "doc_type": "compliance",
        "section_zh": "利益冲突申报",
        "section_en": "Conflict of Interest",
        "zh": "员工应在知悉潜在利益冲突后的 5 个工作日内通过合规系统申报，包括亲属任职、外部兼职与关联交易。",
        "en": "Employees must declare potential conflicts of interest within 5 working days of becoming aware, including relatives' employment, outside roles and related-party transactions.",
        "anchor_zh": "5 个工作日内通过合规系统申报",
        "anchor_en": "within 5 working days of becoming aware",
        "q_zh": "发现利益冲突后需要在多久内申报？",
        "q_en": "How soon must a conflict of interest be declared?",
        "a_zh": "在知悉后的 5 个工作日内通过合规系统申报。",
        "a_en": "Within 5 working days of becoming aware, via the compliance system.",
    },
    {
        "key": "data_classification",
        "doc_type": "compliance",
        "section_zh": "数据分级",
        "section_en": "Data Classification",
        "zh": "公司数据按敏感程度分为 4 级：公开、内部、机密、绝密；机密及以上级别的数据不得存储在个人设备。",
        "en": "Company data is classified into 4 levels: Public, Internal, Confidential and Restricted. Data at Confidential level or above must not be stored on personal devices.",
        "anchor_zh": "分为 4 级",
        "anchor_en": "classified into 4 levels",
        "q_zh": "公司数据分为几个等级？",
        "q_en": "How many data classification levels does the company use?",
        "a_zh": "分为 4 级：公开、内部、机密、绝密；机密及以上不得存于个人设备。",
        "a_en": "4 levels: Public, Internal, Confidential, Restricted; Confidential and above must not be stored on personal devices.",
    },
    {
        "key": "trading_blackout",
        "doc_type": "compliance",
        "section_zh": "内幕信息与交易窗口",
        "section_en": "Inside Information and Trading Window",
        "zh": "在季度财报发布前 30 天至发布后 2 个交易日内，知悉内幕信息的员工不得买卖公司证券。",
        "en": "From 30 days before quarterly earnings release until 2 trading days after, employees with inside information must not trade company securities.",
        "anchor_zh": "财报发布前 30 天",
        "anchor_en": "30 days before quarterly earnings release",
        "q_zh": "财报前的禁止交易窗口有多长？",
        "q_en": "How long is the trading blackout before earnings?",
        "a_zh": "财报发布前 30 天至发布后 2 个交易日内禁止交易。",
        "a_en": "From 30 days before the release until 2 trading days after.",
    },
    {
        "key": "reporting_channel",
        "doc_type": "compliance",
        "section_zh": "举报渠道",
        "section_en": "Whistleblowing Channel",
        "zh": "员工可通过合规邮箱 ethics-cn@example-internal.com 或热线 400-820-1234 进行实名或匿名举报，受理后 10 个工作日内反馈。",
        "en": "Employees may report concerns via the compliance mailbox ethics-cn@example-internal.com or the hotline 400-820-1234, anonymously if preferred. Feedback is provided within 10 working days.",
        "anchor_zh": "合规邮箱",
        "anchor_en": "compliance mailbox",
        "q_zh": "合规举报的渠道有哪些？",
        "q_en": "What channels are available for compliance reporting?",
        "a_zh": "可通过合规邮箱或热线举报，支持实名与匿名，受理后 10 个工作日内反馈。",
        "a_en": "Compliance mailbox or hotline, anonymous reporting supported, with feedback within 10 working days.",
    },
    {
        "key": "audit_record_retention",
        "doc_type": "compliance",
        "section_zh": "审计记录保存",
        "section_en": "Audit Record Retention",
        "zh": "合规审计记录须至少保存 7 年，到期销毁须经合规负责人与法务共同审批。",
        "en": "Compliance audit records must be retained for at least 7 years. Destruction after retention requires joint approval by the Compliance Head and Legal.",
        "anchor_zh": "至少保存 7 年",
        "anchor_en": "retained for at least 7 years",
        "q_zh": "合规审计记录需要保存多久？",
        "q_en": "How long must compliance audit records be retained?",
        "a_zh": "至少保存 7 年，到期销毁需合规负责人与法务共同审批。",
        "a_en": "At least 7 years; destruction requires joint approval by Compliance Head and Legal.",
    },
    {
        "key": "third_party_due_diligence",
        "doc_type": "compliance",
        "section_zh": "第三方尽调",
        "section_en": "Third-Party Due Diligence",
        "zh": "与外部供应商、代理商签约前必须完成第三方尽职调查，高风险主体需提交合规委员会审议。",
        "en": "Third-party due diligence must be completed before signing with external suppliers or agents. High-risk entities require review by the Compliance Committee.",
        "anchor_zh": "签约前必须完成第三方尽职调查",
        "anchor_en": "before signing with external suppliers",
        "q_zh": "第三方尽调需要在什么时候完成？",
        "q_en": "When must third-party due diligence be completed?",
        "a_zh": "必须在签约前完成；高风险主体还需提交合规委员会审议。",
        "a_en": "Before signing; high-risk entities also require Compliance Committee review.",
    },
    {
        "key": "anti_corruption_training",
        "doc_type": "compliance",
        "section_zh": "反腐培训",
        "section_en": "Anti-Corruption Training",
        "zh": "全体员工每年须完成不少于 2 小时的反腐败与商业道德培训，未完成者不得参与晋升评审。",
        "en": "All employees must complete at least 2 hours of anti-corruption and business ethics training annually. Completion is required for promotion review.",
        "anchor_zh": "不少于 2 小时的反腐败",
        "anchor_en": "at least 2 hours of anti-corruption",
        "q_zh": "每年的反腐培训要求多少小时？",
        "q_en": "How many hours of anti-corruption training are required annually?",
        "a_zh": "每年不少于 2 小时，未完成者不得参与晋升评审。",
        "a_en": "At least 2 hours per year; completion is required for promotion review.",
    },
    # ---------------- 技术规范 ----------------
    {
        "key": "rate_limit",
        "doc_type": "tech_spec",
        "section_zh": "速率限制",
        "section_en": "Rate Limiting",
        "zh": "开放平台接口对每个租户限制 1000 QPS，超出后返回 429 并在响应头返回重试等待秒数。",
        "en": "Open platform APIs are limited to 1000 QPS per tenant. Exceeding the limit returns 429 with a retry-after header.",
        "anchor_zh": "限制 1000 QPS",
        "anchor_en": "limited to 1000 QPS per tenant",
        "q_zh": "接口的速率限制是多少？",
        "q_en": "What is the API rate limit?",
        "a_zh": "每个租户 1000 QPS，超出返回 429 并给出重试等待时间。",
        "a_en": "1000 QPS per tenant; exceeding it returns 429 with retry-after.",
    },
    {
        "key": "access_token_ttl",
        "doc_type": "tech_spec",
        "section_zh": "认证与令牌",
        "section_en": "Authentication and Tokens",
        "zh": "系统采用 OAuth2 客户端凭证模式，访问令牌有效期为 3600 秒，刷新令牌有效期为 14 天。",
        "en": "The platform uses OAuth2 client credentials. Access tokens are valid for 3600 seconds and refresh tokens for 14 days.",
        "anchor_zh": "访问令牌有效期为 3600 秒",
        "anchor_en": "Access tokens are valid for 3600 seconds",
        "q_zh": "访问令牌的有效期是多久？",
        "q_en": "How long is an access token valid?",
        "a_zh": "访问令牌有效期 3600 秒，刷新令牌 14 天。",
        "a_en": "Access tokens 3600 seconds; refresh tokens 14 days.",
    },
    {
        "key": "log_retention",
        "doc_type": "tech_spec",
        "section_zh": "日志保留",
        "section_en": "Log Retention",
        "zh": "应用日志在线保留 180 天，归档日志保留 2 年；日志中不得记录明文个人敏感信息。",
        "en": "Application logs are retained online for 180 days and archived for 2 years. Logs must not contain plaintext sensitive personal information.",
        "anchor_zh": "在线保留 180 天",
        "anchor_en": "retained online for 180 days",
        "q_zh": "应用日志在线保留多久？",
        "q_en": "How long are application logs retained online?",
        "a_zh": "在线保留 180 天，归档保留 2 年，且不得记录明文敏感信息。",
        "a_en": "180 days online, 2 years archived, with no plaintext sensitive data.",
    },
    {
        "key": "encryption_standard",
        "doc_type": "tech_spec",
        "section_zh": "加密标准",
        "section_en": "Encryption Standards",
        "zh": "数据静态存储采用 AES-256 加密，传输链路采用 TLS 1.3，禁止使用已被废弃的 TLS 1.0 与 1.1。",
        "en": "Data at rest uses AES-256 encryption and data in transit uses TLS 1.3. Deprecated TLS 1.0 and 1.1 are prohibited.",
        "anchor_zh": "静态存储采用 AES-256 加密",
        "anchor_en": "at rest uses AES-256 encryption",
        "q_zh": "数据传输和存储分别用什么加密标准？",
        "q_en": "Which encryption standards are used for data at rest and in transit?",
        "a_zh": "静态存储 AES-256，传输 TLS 1.3，禁用 TLS 1.0/1.1。",
        "a_en": "AES-256 at rest and TLS 1.3 in transit; TLS 1.0/1.1 are prohibited.",
    },
    {
        "key": "pagination_defaults",
        "doc_type": "tech_spec",
        "section_zh": "分页约定",
        "section_en": "Pagination",
        "zh": "列表接口默认每页返回 20 条记录，单页最大 200 条；超出最大值的请求参数将被拒绝。",
        "en": "List endpoints return 20 records per page by default and at most 200 per page. Requests exceeding the maximum are rejected.",
        "anchor_zh": "默认每页返回 20 条记录",
        "anchor_en": "20 records per page by default",
        "q_zh": "列表接口默认每页返回多少条？",
        "q_en": "How many records does a list endpoint return per page by default?",
        "a_zh": "默认 20 条，单页最大 200 条。",
        "a_en": "20 by default, maximum 200 per page.",
    },
    {
        "key": "gateway_timeout",
        "doc_type": "tech_spec",
        "section_zh": "超时设置",
        "section_en": "Timeouts",
        "zh": "API 网关对同步请求的超时设置为 30 秒，超过后返回 504；批处理任务须改用异步任务接口。",
        "en": "The API gateway times out synchronous requests after 30 seconds and returns 504. Batch workloads must use the asynchronous task API.",
        "anchor_zh": "超时设置为 30 秒",
        "anchor_en": "times out synchronous requests after 30 seconds",
        "q_zh": "API 网关的超时时间是多少？",
        "q_en": "What is the API gateway timeout?",
        "a_zh": "同步请求 30 秒，超时返回 504，批处理需改用异步接口。",
        "a_en": "30 seconds for synchronous requests, returning 504; batch work must use the async API.",
    },
    {
        "key": "api_version_header",
        "doc_type": "tech_spec",
        "section_zh": "版本管理",
        "section_en": "API Versioning",
        "zh": "接口版本通过请求头 X-API-Version 指定，未指定时默认使用 v2；旧版本在停止支持前提供 12 个月过渡期。",
        "en": "API versions are selected with the X-API-Version header, defaulting to v2. Deprecated versions get a 12-month transition period.",
        "anchor_zh": "请求头 X-API-Version 指定",
        "anchor_en": "X-API-Version header",
        "q_zh": "如何指定接口版本？",
        "q_en": "How is the API version specified?",
        "a_zh": "通过请求头 X-API-Version 指定，默认 v2，旧版本有 12 个月过渡期。",
        "a_en": "Via the X-API-Version header, defaulting to v2, with a 12-month transition for deprecated versions.",
    },
    {
        "key": "error_code_format",
        "doc_type": "tech_spec",
        "section_zh": "错误码规范",
        "section_en": "Error Codes",
        "zh": "错误码为 5 位数字，前两位标识服务域，后三位标识具体错误；错误响应体必须包含 trace_id 便于排查。",
        "en": "Error codes are 5 digits: the first two identify the service domain and the last three the specific error. Error responses must include a trace_id.",
        "anchor_zh": "错误码为 5 位数字",
        "anchor_en": "Error codes are 5 digits",
        "q_zh": "错误码的格式是什么？",
        "q_en": "What is the error code format?",
        "a_zh": "5 位数字，前两位为服务域，后三位为具体错误，响应需含 trace_id。",
        "a_en": "5 digits: two for the service domain, three for the specific error, with trace_id in the response.",
    },
    # ---------------- 架构文档 ----------------
    {
        "key": "primary_database",
        "doc_type": "architecture",
        "section_zh": "数据存储",
        "section_en": "Data Storage",
        "zh": "核心交易数据存储于 PostgreSQL 16 主从集群，采用同步复制保证零数据丢失，读请求路由至只读副本。",
        "en": "Core transactional data is stored in a PostgreSQL 16 primary-replica cluster with synchronous replication for zero data loss. Reads are routed to replicas.",
        "anchor_zh": "PostgreSQL 16 主从集群",
        "anchor_en": "PostgreSQL 16 primary-replica cluster",
        "q_zh": "核心交易数据使用什么数据库？",
        "q_en": "Which database stores core transactional data?",
        "a_zh": "PostgreSQL 16 主从集群，同步复制，读请求路由至只读副本。",
        "a_en": "A PostgreSQL 16 primary-replica cluster with synchronous replication; reads go to replicas.",
    },
    {
        "key": "message_queue",
        "doc_type": "architecture",
        "section_zh": "消息队列",
        "section_en": "Messaging",
        "zh": "异步事件通过 Kafka 传输，关键主题配置 3 副本与 acks=all，保证消息不丢失。",
        "en": "Asynchronous events flow through Kafka. Critical topics use 3 replicas with acks=all to prevent message loss.",
        "anchor_zh": "配置 3 副本与 acks=all",
        "anchor_en": "use 3 replicas with acks=all",
        "q_zh": "消息队列的副本配置是怎样的？",
        "q_en": "What replication is configured for the message queue?",
        "a_zh": "Kafka 关键主题配置 3 副本与 acks=all。",
        "a_en": "Kafka critical topics use 3 replicas with acks=all.",
    },
    {
        "key": "cache_cluster",
        "doc_type": "architecture",
        "section_zh": "缓存层",
        "section_en": "Cache Layer",
        "zh": "缓存层由 6 节点 Redis 集群组成，采用一致性哈希分片，热点数据设置 5 分钟过期时间。",
        "en": "The cache layer is a 6-node Redis cluster with consistent hashing sharding. Hot data expires after 5 minutes.",
        "anchor_zh": "6 节点 Redis 集群",
        "anchor_en": "6-node Redis cluster",
        "q_zh": "缓存集群有多少个节点？",
        "q_en": "How many nodes are in the cache cluster?",
        "a_zh": "6 节点 Redis 集群，一致性哈希分片，热点数据 5 分钟过期。",
        "a_en": "A 6-node Redis cluster with consistent hashing; hot data expires in 5 minutes.",
    },
    {
        "key": "api_gateway",
        "doc_type": "architecture",
        "section_zh": "接入网关",
        "section_en": "API Gateway",
        "zh": "所有外部流量经统一网关 Kong 接入，网关负责认证、限流、灰度路由与访问日志采集。",
        "en": "All external traffic enters through the unified Kong gateway, which handles authentication, rate limiting, canary routing and access logging.",
        "anchor_zh": "统一网关 Kong 接入",
        "anchor_en": "unified Kong gateway",
        "q_zh": "外部流量通过什么网关接入？",
        "q_en": "Which gateway handles external traffic?",
        "a_zh": "统一网关 Kong，负责认证、限流、灰度路由与访问日志。",
        "a_en": "The unified Kong gateway, handling authentication, rate limiting, canary routing and access logging.",
    },
    {
        "key": "deployment_topology",
        "doc_type": "architecture",
        "section_zh": "部署拓扑",
        "section_en": "Deployment Topology",
        "zh": "服务部署于 Kubernetes 集群，跨 3 个可用区运行，每个服务至少 2 个副本并配置反亲和性。",
        "en": "Services run on a Kubernetes cluster across 3 availability zones, with at least 2 replicas per service and anti-affinity rules.",
        "anchor_zh": "跨 3 个可用区运行",
        "anchor_en": "across 3 availability zones",
        "q_zh": "服务部署在几个可用区？",
        "q_en": "How many availability zones are services deployed across?",
        "a_zh": "跨 3 个可用区，每服务至少 2 个副本并配置反亲和性。",
        "a_en": "3 availability zones, with at least 2 replicas per service and anti-affinity.",
    },
    {
        "key": "observability_stack",
        "doc_type": "architecture",
        "section_zh": "可观测体系",
        "section_en": "Observability",
        "zh": "可观测体系由 Prometheus 采集指标、Loki 汇聚日志、Tempo 存储链路追踪数据，三者通过 trace_id 关联。",
        "en": "The observability stack uses Prometheus for metrics, Loki for logs and Tempo for traces, correlated by trace_id.",
        "anchor_zh": "Prometheus 采集指标",
        "anchor_en": "Prometheus for metrics",
        "q_zh": "可观测体系由哪些组件构成？",
        "q_en": "Which components make up the observability stack?",
        "a_zh": "Prometheus 采集指标、Loki 汇聚日志、Tempo 存储链路追踪，通过 trace_id 关联。",
        "a_en": "Prometheus for metrics, Loki for logs, Tempo for traces, correlated by trace_id.",
    },
    {
        "key": "backup_policy",
        "doc_type": "architecture",
        "section_zh": "备份策略",
        "section_en": "Backup Policy",
        "zh": "数据库每日执行一次全量备份并保留 35 天，每 6 小时执行一次增量备份，季度进行恢复演练。",
        "en": "Databases are backed up in full daily with 35-day retention, incrementally every 6 hours, and restore drills run quarterly.",
        "anchor_zh": "全量备份并保留 35 天",
        "anchor_en": "full daily with 35-day retention",
        "q_zh": "数据库备份保留多久？",
        "q_en": "How long are database backups retained?",
        "a_zh": "每日全量备份保留 35 天，每 6 小时增量备份，季度恢复演练。",
        "a_en": "Daily full backups retained 35 days, incremental every 6 hours, quarterly restore drills.",
    },
    {
        "key": "availability_sla",
        "doc_type": "architecture",
        "section_zh": "可用性目标",
        "section_en": "Availability Target",
        "zh": "核心服务的可用性目标为 99.95%，月度不可用时间预算约为 21 分钟。",
        "en": "The availability target for core services is 99.95%, corresponding to a monthly unavailability budget of about 21 minutes.",
        "anchor_zh": "可用性目标为 99.95%",
        "anchor_en": "availability target for core services is 99.95%",
        "q_zh": "核心服务的可用性目标是多少？",
        "q_en": "What is the availability target for core services?",
        "a_zh": "99.95%，月度不可用时间预算约 21 分钟。",
        "a_en": "99.95%, about 21 minutes of monthly unavailability budget.",
    },
]


def validate() -> None:
    """校验锚点唯一性：锚点必须只出现在对应事实的文本中。"""
    from ..textutil import normalize_for_match

    keys = [f["key"] for f in FACTS]
    assert len(keys) == len(set(keys)), "存在重复的 fact key"
    for fact in FACTS:
        others_zh = normalize_for_match(" ".join(f["zh"] for f in FACTS if f["key"] != fact["key"]))
        others_en = normalize_for_match(" ".join(f["en"] for f in FACTS if f["key"] != fact["key"]))
        assert normalize_for_match(fact["anchor_zh"]) not in others_zh, f"锚点冲突(zh): {fact['key']}"
        assert normalize_for_match(fact["anchor_en"]) not in others_en, f"锚点冲突(en): {fact['key']}"


def facts_by_key() -> dict[str, dict[str, Any]]:
    return {f["key"]: f for f in FACTS}
